"""Allow nullable _password_hash for testing

Revision ID: 67043a7a9598
Revises: a44201ea39e5
Create Date: 2025-02-03 10:49:56.576887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67043a7a9598'
down_revision = 'a44201ea39e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
